pngcrush -ow -rem allb -reduce add.png
pngcrush -ow -rem allb -reduce cairo-clock.png
pngcrush -ow -rem allb -reduce calendar.png
pngcrush -ow -rem allb -reduce calendar_view_day.png
pngcrush -ow -rem allb -reduce calendar_view_month.png
pngcrush -ow -rem allb -reduce calendar_view_week.png
pngcrush -ow -rem allb -reduce cap.png
pngcrush -ow -rem allb -reduce clock_.png
pngcrush -ow -rem allb -reduce clock_red.png
pngcrush -ow -rem allb -reduce clock_red48.png
pngcrush -ow -rem allb -reduce cross.png
pngcrush -ow -rem allb -reduce cut.png
pngcrush -ow -rem allb -reduce date_previous_gray.png
pngcrush -ow -rem allb -reduce date_task.png
pngcrush -ow -rem allb -reduce delicious.png
pngcrush -ow -rem allb -reduce edit.png
pngcrush -ow -rem allb -reduce exit.png
pngcrush -ow -rem allb -reduce fileclose.png
pngcrush -ow -rem allb -reduce fileprint.png
pngcrush -ow -rem allb -reduce gnome-day.png
pngcrush -ow -rem allb -reduce go-next.png
pngcrush -ow -rem allb -reduce go-previous.png
pngcrush -ow -rem allb -reduce key_q.png
pngcrush -ow -rem allb -reduce list-add.png
pngcrush -ow -rem allb -reduce list-remove.png
pngcrush -ow -rem allb -reduce new.png
pngcrush -ow -rem allb -reduce open.png
pngcrush -ow -rem allb -reduce paste.png
pngcrush -ow -rem allb -reduce remove.png
pngcrush -ow -rem allb -reduce report.png
pngcrush -ow -rem allb -reduce save.png
pngcrush -ow -rem allb -reduce thumb_down.png
pngcrush -ow -rem allb -reduce zoomin.png
pngcrush -ow -rem allb -reduce zoomout.png
