pngcrush -ow -rem allb -reduce address_16.png
pngcrush -ow -rem allb -reduce address_32.png
pngcrush -ow -rem allb -reduce address_48.png
pngcrush -ow -rem allb -reduce address_64.png
pngcrush -ow -rem allb -reduce block_16.png
pngcrush -ow -rem allb -reduce block_32.png
pngcrush -ow -rem allb -reduce block_48.png
pngcrush -ow -rem allb -reduce block_64.png
pngcrush -ow -rem allb -reduce bookmark_16.png
pngcrush -ow -rem allb -reduce bookmark_32.png
pngcrush -ow -rem allb -reduce bookmark_48.png
pngcrush -ow -rem allb -reduce bookmark_64.png
pngcrush -ow -rem allb -reduce briefcase_16.png
pngcrush -ow -rem allb -reduce briefcase_32.png
pngcrush -ow -rem allb -reduce briefcase_48.png
pngcrush -ow -rem allb -reduce briefcase_64.png
pngcrush -ow -rem allb -reduce bubble_16.png
pngcrush -ow -rem allb -reduce bubble_32.png
pngcrush -ow -rem allb -reduce bubble_48.png
pngcrush -ow -rem allb -reduce bubble_64.png
pngcrush -ow -rem allb -reduce buy_16.png
pngcrush -ow -rem allb -reduce buy_32.png
pngcrush -ow -rem allb -reduce buy_48.png
pngcrush -ow -rem allb -reduce buy_64.png
pngcrush -ow -rem allb -reduce calendar_16.png
pngcrush -ow -rem allb -reduce calendar_32.png
pngcrush -ow -rem allb -reduce calendar_48.png
pngcrush -ow -rem allb -reduce calendar_64.png
pngcrush -ow -rem allb -reduce clipboard_16.png
pngcrush -ow -rem allb -reduce clipboard_32.png
pngcrush -ow -rem allb -reduce clipboard_48.png
pngcrush -ow -rem allb -reduce clipboard_64.png
pngcrush -ow -rem allb -reduce clock_16.png
pngcrush -ow -rem allb -reduce clock_32.png
pngcrush -ow -rem allb -reduce clock_48.png
pngcrush -ow -rem allb -reduce clock_64.png
pngcrush -ow -rem allb -reduce delete_16.png
pngcrush -ow -rem allb -reduce delete_32.png
pngcrush -ow -rem allb -reduce delete_48.png
pngcrush -ow -rem allb -reduce delete_64.png
pngcrush -ow -rem allb -reduce diagram_16.png
pngcrush -ow -rem allb -reduce diagram_32.png
pngcrush -ow -rem allb -reduce diagram_48.png
pngcrush -ow -rem allb -reduce diagram_64.png
pngcrush -ow -rem allb -reduce document_16.png
pngcrush -ow -rem allb -reduce document_32.png
pngcrush -ow -rem allb -reduce document_48.png
pngcrush -ow -rem allb -reduce document_64.png
pngcrush -ow -rem allb -reduce down_16.png
pngcrush -ow -rem allb -reduce down_32.png
pngcrush -ow -rem allb -reduce down_48.png
pngcrush -ow -rem allb -reduce down_64.png
pngcrush -ow -rem allb -reduce flag_16.png
pngcrush -ow -rem allb -reduce flag_32.png
pngcrush -ow -rem allb -reduce flag_48.png
pngcrush -ow -rem allb -reduce flag_64.png
pngcrush -ow -rem allb -reduce folder_16.png
pngcrush -ow -rem allb -reduce folder_32.png
pngcrush -ow -rem allb -reduce folder_48.png
pngcrush -ow -rem allb -reduce folder_64.png
pngcrush -ow -rem allb -reduce gear_16.png
pngcrush -ow -rem allb -reduce gear_32.png
pngcrush -ow -rem allb -reduce gear_48.png
pngcrush -ow -rem allb -reduce gear_64.png
pngcrush -ow -rem allb -reduce globe_16.png
pngcrush -ow -rem allb -reduce globe_32.png
pngcrush -ow -rem allb -reduce globe_48.png
pngcrush -ow -rem allb -reduce globe_64.png
pngcrush -ow -rem allb -reduce heart_16.png
pngcrush -ow -rem allb -reduce heart_32.png
pngcrush -ow -rem allb -reduce heart_48.png
pngcrush -ow -rem allb -reduce heart_64.png
pngcrush -ow -rem allb -reduce help_16.png
pngcrush -ow -rem allb -reduce help_32.png
pngcrush -ow -rem allb -reduce help_48.png
pngcrush -ow -rem allb -reduce help_64.png
pngcrush -ow -rem allb -reduce home_16.png
pngcrush -ow -rem allb -reduce home_32.png
pngcrush -ow -rem allb -reduce home_48.png
pngcrush -ow -rem allb -reduce home_64.png
pngcrush -ow -rem allb -reduce info_16.png
pngcrush -ow -rem allb -reduce info_32.png
pngcrush -ow -rem allb -reduce info_48.png
pngcrush -ow -rem allb -reduce info_64.png
pngcrush -ow -rem allb -reduce key_16.png
pngcrush -ow -rem allb -reduce key_32.png
pngcrush -ow -rem allb -reduce key_48.png
pngcrush -ow -rem allb -reduce key_64.png
pngcrush -ow -rem allb -reduce label_16.png
pngcrush -ow -rem allb -reduce label_32.png
pngcrush -ow -rem allb -reduce label_48.png
pngcrush -ow -rem allb -reduce label_64.png
pngcrush -ow -rem allb -reduce left_16.png
pngcrush -ow -rem allb -reduce left_32.png
pngcrush -ow -rem allb -reduce left_48.png
pngcrush -ow -rem allb -reduce left_64.png
pngcrush -ow -rem allb -reduce letter_16.png
pngcrush -ow -rem allb -reduce letter_32.png
pngcrush -ow -rem allb -reduce letter_48.png
pngcrush -ow -rem allb -reduce letter_64.png
pngcrush -ow -rem allb -reduce monitor_16.png
pngcrush -ow -rem allb -reduce monitor_32.png
pngcrush -ow -rem allb -reduce monitor_48.png
pngcrush -ow -rem allb -reduce monitor_64.png
pngcrush -ow -rem allb -reduce pencil_16.png
pngcrush -ow -rem allb -reduce pencil_32.png
pngcrush -ow -rem allb -reduce pencil_48.png
pngcrush -ow -rem allb -reduce pencil_64.png
pngcrush -ow -rem allb -reduce plus_16.png
pngcrush -ow -rem allb -reduce plus_32.png
pngcrush -ow -rem allb -reduce plus_48.png
pngcrush -ow -rem allb -reduce plus_64.png
pngcrush -ow -rem allb -reduce present_16.png
pngcrush -ow -rem allb -reduce present_32.png
pngcrush -ow -rem allb -reduce present_48.png
pngcrush -ow -rem allb -reduce present_64.png
pngcrush -ow -rem allb -reduce print_16.png
pngcrush -ow -rem allb -reduce print_32.png
pngcrush -ow -rem allb -reduce print_48.png
pngcrush -ow -rem allb -reduce print_64.png
pngcrush -ow -rem allb -reduce right_16.png
pngcrush -ow -rem allb -reduce right_32.png
pngcrush -ow -rem allb -reduce right_48.png
pngcrush -ow -rem allb -reduce right_64.png
pngcrush -ow -rem allb -reduce save_16.png
pngcrush -ow -rem allb -reduce save_32.png
pngcrush -ow -rem allb -reduce save_48.png
pngcrush -ow -rem allb -reduce save_64.png
pngcrush -ow -rem allb -reduce search_16.png
pngcrush -ow -rem allb -reduce search_32.png
pngcrush -ow -rem allb -reduce search_48.png
pngcrush -ow -rem allb -reduce search_64.png
pngcrush -ow -rem allb -reduce shield_16.png
pngcrush -ow -rem allb -reduce shield_32.png
pngcrush -ow -rem allb -reduce shield_48.png
pngcrush -ow -rem allb -reduce shield_64.png
pngcrush -ow -rem allb -reduce statistics_16.png
pngcrush -ow -rem allb -reduce statistics_32.png
pngcrush -ow -rem allb -reduce statistics_48.png
pngcrush -ow -rem allb -reduce statistics_64.png
pngcrush -ow -rem allb -reduce stop_16.png
pngcrush -ow -rem allb -reduce stop_32.png
pngcrush -ow -rem allb -reduce stop_48.png
pngcrush -ow -rem allb -reduce stop_64.png
pngcrush -ow -rem allb -reduce tick_16.png
pngcrush -ow -rem allb -reduce tick_32.png
pngcrush -ow -rem allb -reduce tick_48.png
pngcrush -ow -rem allb -reduce tick_64.png
pngcrush -ow -rem allb -reduce trash_16.png
pngcrush -ow -rem allb -reduce trash_32.png
pngcrush -ow -rem allb -reduce trash_48.png
pngcrush -ow -rem allb -reduce trash_64.png
pngcrush -ow -rem allb -reduce up_16.png
pngcrush -ow -rem allb -reduce up_32.png
pngcrush -ow -rem allb -reduce up_48.png
pngcrush -ow -rem allb -reduce up_64.png
pngcrush -ow -rem allb -reduce user_16.png
pngcrush -ow -rem allb -reduce user_32.png
pngcrush -ow -rem allb -reduce user_48.png
pngcrush -ow -rem allb -reduce user_64.png
pngcrush -ow -rem allb -reduce wallet_16.png
pngcrush -ow -rem allb -reduce wallet_32.png
pngcrush -ow -rem allb -reduce wallet_48.png
pngcrush -ow -rem allb -reduce wallet_64.png
pngcrush -ow -rem allb -reduce warning_16.png
pngcrush -ow -rem allb -reduce warning_32.png
pngcrush -ow -rem allb -reduce warning_48.png
pngcrush -ow -rem allb -reduce warning_64.png